version: "3.7"

services:
    web-server:
        container_name: web-server
        build:
            context: ./docker/web-server/
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
